version: "3"

services:
  memcached:
    image: memcached:1.5.21
    container_name: memcached
    command: memcached -vv
    ports:
      - 11211:11211

  memproxy:
    build: .
    environment:
      - AUTH_USER=${AUTH_USER}
      - AUTH_PASS=${AUTH_PASS}
      - DEBUG=memcache*
      - PORT=${PORT:-3000}
      - UPSTREAM=${UPSTREAM:-memcached:11211}
    command: npm start
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    depends_on:
      - memcached
